161028_Django_Day15/mysite-project/django_app/mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
# from blog import views as blog_views
from mysite import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # blog/urls.py를 사용하지 않고 루트 urls.py를 사용할 경우
    # url(r'^$', blog_views.post_list, name='post_list'),

    # blog/urls.py의 내용을 사용할 경우
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^video/', include('video.urls', namespace='video')),
    url(r'^sns/', include('sns.urls', namespace='sns')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

161028_Django_Day15/mysite-project/django_app/photo/urls.py
from django.conf.urls import url
from . import views
from . import ajax

urlpatterns = [
    url(r'^$', views.album_list, name='album_list'),
    url(r'^album/add/$', views.album_add, name='album_add'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.album_detail, name='album_detail'),
    url(r'^album/(?P<album_pk>[0-9]+)/photo/add/$', views.photo_add, name='photo_add'),
    url(r'^album/(?P<album_pk>[0-9]+)/photo/multi/add/$', views.photo_multi_add, name='photo_multi_add'),
    url(r'^photo/(?P<pk>[0-9]+)/$', views.photo_detail, name='photo_detail'),
    url(r'^photo/(?P<pk>[0-9]+)/(?P<like_type>\w+)/$', views.photo_like, name='photo_like'),

    url(r'^ajax/photo/(?P<pk>[0-9]+)/(?P<like_type>\w+)/$', ajax.photo_like, name='ajax_photo_like'),
]

161028_Django_Day15/mysite-project/django_app/sns/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^facebook/friends_ranking/$', views.friends_ranking, name='friends_ranking'),
]

161028_Django_Day15/mysite-project/django_app/photo/models.py
from django.db import models
from django.conf import settings
from mysite.utils.models import BaseModel
from member.models import MyUser as User
"""
Album
    title : CharField
    owner : ForeignKey
    description : CharField

Photo
    Album : ForeignKey
    owner : ForeignKey
    title : CharField
    description : CharField
    img : ImageField

Photo좋아요를 구현하고싶으면 어떻게해야될까요?
좋아요에는 해당 Photo, User, 좋아요누른시간이 기록됩니다
"""


class Album(BaseModel):
    title = models.CharField(max_length=30)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    description = models.CharField(max_length=80, blank=True)


class Photo(BaseModel):
    album = models.ForeignKey(Album)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=80, blank=True)
    img = models.ImageField(upload_to='photo')
    img_thumbnail = models.ImageField(upload_to='photo/thumbnail', blank=True)
    # M2M Field를 사용해서 좋아요 내용을 거치도록 합니다 (중간자 모델)
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#intermediary-manytomany
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='PhotoLike', related_name='photo_set_like_users')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='PhotoDislike', related_name='photo_set_dislike_users')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        image_changed = False

        # save전, img필드의 내용이 변했는지 확인
        # 기존에 DB에 저장되어있을 경우에만 지정(self.pk가 없을경우 에러)
        if self.pk:
            ori = Photo.objects.get(pk=self.pk)
            if ori.img != self.img:
                image_changed = True

        # img는 있는데 img_thumbnail은 없을 경우
        if self.img and not self.img_thumbnail:
            image_changed = True

        super().save(*args, **kwargs)
        if image_changed:
            self.make_thumbnail()

    def url_thumbnail(self):
        return self.url_field('img_thumbnail', default='/static/img/default.jpg')

    def make_thumbnail(self):
        import os
        from PIL import Image, ImageOps
        from io import BytesIO, StringIO, FileIO
        from django.core.files.base import ContentFile
        from django.core.files.storage import default_storage

        size = (300, 300)
        # Default storage에서 FileField내용 읽어오기
        f = default_storage.open(self.img)
        print('f : %s' % f)

        # Image.open으로 파일을 Image인스턴스화 (image)
        image = Image.open(f)
        # Image.format은 JPEG, PNG, BMP등 포맷정보를 나타냄
        ftype = image.format
        print('ftype : %s' % ftype)

        # ImageOps.fit메서드를 이용해서 썸네일이미지 생성
        image = ImageOps.fit(image, size, Image.ANTIALIAS)

        # 기존에 있던 img의 경로와 확장자를 가져옴
        path, ext = os.path.splitext(self.img.name)
        name = os.path.basename(path)

        # 기존파일명_thumb.확장자 형태가 됨
        thumbnail_name = '%s_thumb%s' % (name, ext)

        # 임시 파일로 취급되는 객체 생성
        temp_file = BytesIO()
        image.save(temp_file, ftype)
        temp_file.seek(0)

        # img_thumbnail필드에 해당 파일내용을 저장
        # Django의 FileField에 내용을 저장할때는 ContentFile형식이어야 함
        content_file = ContentFile(temp_file.read())
        self.img_thumbnail.save(thumbnail_name, content_file)

        # 열었던 파일 닫아줌
        temp_file.close()
        content_file.close()
        f.close()
        return True







class PhotoLike(BaseModel):
    photo = models.ForeignKey(Photo)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)


class PhotoDislike(BaseModel):
    photo = models.ForeignKey(Photo)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

161028_Django_Day15/mysite-project/django_app/photo/forms/album.py
from django import forms

__all__ = [
    'AlbumForm',
]


class AlbumForm(forms.Form):
    title = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        })
    )
    description = forms.CharField(
        max_length=80,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
        })
    )

    # 특정 field의 내용을 cleaned_data에서 후처리 하고 싶을때
    # def clean_title(self):
    #     ori_title = self.cleaned_data['title']
    #     return 'Album (%s)' % ori_title

161028_Django_Day15/mysite-project/django_app/photo/forms/photo.py
from django import forms

__all__ = [
    'PhotoForm',
    'MultiPhotoForm',
]


class PhotoForm(forms.Form):
    title = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        })
    )
    description = forms.CharField(
        max_length=80,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
        })
    )
    img = forms.ImageField(required=True)


class MultiPhotoForm(forms.Form):
    title = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        })
    )
    description = forms.CharField(
        max_length=80,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
        })
    )
    img = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'multiple': True
            }
        )
    )

161028_Django_Day15/mysite-project/django_app/photo/views.py
from django.shortcuts import render

# Create your views here.

161028_Django_Day15/mysite-project/django_app/photo/views/album.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from ..models import Album
from ..forms import AlbumForm

__all__ = [
    'album_list',
    'album_add',
    'album_detail',
]


def album_list(request):
    albums = Album.objects.all()
    context = {
        'albums': albums,
    }
    return render(request, 'photo/album_list.html', context)


def album_add(request):
    if request.method == 'POST':
        form = AlbumForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            Album.objects.create(
                title=title,
                description=description,
                owner=request.user,
            )
            return redirect('photo:album_list')
    else:
        form = AlbumForm()
    context = {
        'form': form,
    }
    return render(request, 'photo/album_add.html', context)


def album_detail(request, pk):
    album = get_object_or_404(Album, pk=pk)
    photo_list = album.photo_set.all()
    paginator = Paginator(photo_list, 4)

    page = request.GET.get('page')
    try:
        photos = paginator.page(page)
    except PageNotAnInteger:
        photos = paginator.page(1)
    except EmptyPage:
        photos = paginator.page(paginator.num_pages)

    context = {
        'album': album,
        'photos': photos,
    }
    # template_file = 'photo/album_detail.html'
    template_file = 'photo/ajax_album_detail.html'
    return render(request, template_file, context)

161028_Django_Day15/mysite-project/django_app/photo/views/photo.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.urls import reverse
from ..models import Album, Photo, PhotoLike, PhotoDislike
from ..forms import PhotoForm, MultiPhotoForm

__all__ = [
    'photo_add',
    'photo_multi_add',
    'photo_detail',
    'photo_like',
]


@login_required
def photo_add(request, album_pk):
    album = get_object_or_404(Album, pk=album_pk)
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            # img = request.FILES['img']
            img = form.cleaned_data['img']
            Photo.objects.create(
                album=album,
                owner=request.user,
                title=title,
                description=description,
                img=img,
            )
            return redirect('photo:album_detail', pk=album_pk)
    else:
        form = PhotoForm()
    context = {
        'form': form,
    }
    return render(request, 'photo/photo_add.html', context)


@login_required
def photo_multi_add(request, album_pk):
    album = get_object_or_404(Album, pk=album_pk)
    if request.method == 'POST':
        form = MultiPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            files = request.FILES.getlist('img')
            for index, file in enumerate(files):
                Photo.objects.create(
                    album=album,
                    owner=request.user,
                    title='%s(%s)' % (title, index+1),
                    description='%s(%s)' % (description, index+1),
                    img=file,
                )
            return redirect('photo:album_detail', pk=album_pk)
    else:
        form = MultiPhotoForm()
    context = {
        'form': form,
    }
    return render(request, 'photo/photo_multi_add.html', context)


def photo_detail(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    context = {
        'photo': photo,
    }
    return render(request, 'photo/photo_detail.html', context)


@login_required
@require_POST
def photo_like(request, pk, like_type='like'):
    """
    1. 요청한 유저가 이 사진에 좋아요(또는 싫어요)를 눌렀는가?
    2. 이미 좋아요를 눌렀는데 다시 좋아요를 누른 경우
    3. 이미 좋아요를 눌렀는데 싫어요를 누른 경우
    """
    photo = get_object_or_404(Photo, pk=pk)
    album = photo.album
    next_path = request.GET.get('next')
    like_model = PhotoLike if like_type == 'like' else PhotoDislike
    opposite_model = PhotoDislike if like_type == 'like' else PhotoLike

    user_like_exist = like_model.objects.filter(
        user=request.user,
        photo=photo
    )
    # 요청한 유저가 이미 좋아요(또는 싫어요)를 했는가?
    if user_like_exist.exists():
        user_like_exist.delete()

    # 이미 누르지 않은 경우, 좋아요 처리를 해준다
    else:
        like_model.objects.create(
            user=request.user,
            photo=photo
        )
        # 근데 이사람이 싫어요(또는 반대모델)를 눌러놨을 경우
        # 해당하는 경우를 지워준다
        opposite_model.objects.filter(
            user=request.user,
            photo=photo
        ).delete()

    if next_path:
        return redirect(next_path)
    else:
        return redirect('photo:album_detail', pk=album.pk)

161028_Django_Day15/mysite-project/django_app/templates/photo/ajax_album_detail.html
{% extends 'common/base.html' %}
{% load staticfiles %}

{% block content %}
<div id="album-detail">
	<h4>{{ album.title }}</h4>
	<div>
		<span>{{ album.owner.email }}</span>
		{% if album.description %}
		<span>| {{ album.description }}</span>
		{% endif %}
	</div>
	<a href="{% url 'photo:photo_add' album_pk=album.pk %}" class="btn btn-primary btn-sm btn-top-right">
		<span class="glyphicon glyphicon-plus"></span>
		Add Photo
	</a>
	<a href="{% url 'photo:photo_multi_add' album_pk=album.pk %}" class="btn btn-primary btn-sm btn-top-right" style="margin-top: 40px;">
		<span class="glyphicon glyphicon-plus"></span>
		Add Multi Photo
	</a>
	<div class="photo-list">
		{% for photo in photos %}
		<div class="col-xs-6 col-md-3">
			<div class="thumbnail">
				<a href="{% url 'photo:photo_detail' pk=photo.pk %}">
					<img src="{{ photo.url_thumbnail }}" alt="">
				</a>
				<div class="caption">
					<div>
						<strong>{{ photo.title }}</strong>
					</div>
					<div>
						<span>{{ photo.owner.email }}</span>
						{% if photo.description %}
						<span>| {{ photo.description }}</span>
						{% endif %}
					</div>
					<div class="like-container">

						<button id="btn-photo-{{ photo.pk }}-like" onclick="photoLike({{ photo.pk }}, 'like')" class="btn label label-default">
							<span class="glyphicon glyphicon-thumbs-up"> </span>
							<span id="photo-{{ photo.pk }}-like-count" photo-pk="{{ photo.pk }}">{{ photo.like_users.count }}</span>
						</button>

						<button id="btn-photo-{{ photo.pk }}-dislike" onclick="photoLike({{ photo.pk }}, 'dislike')" class="btn label label-default">
							<span class="glyphicon glyphicon-thumbs-down"> </span>
							<span id="photo-{{ photo.pk }}-dislike-count" photo-pk="{{ photo.pk }}">{{ photo.dislike_users.count }}</span>
						</button>

					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
	<nav>
		<ul class="pager">
			{% if photos.has_previous %}
			<li>
				<a href="?page={{ photos.previous_page_number }}">Prev</a>
			</li>
			{% endif %}

			<li>
				<a href="#">{{ photos.number }} of {{ photos.paginator.num_pages }}</a>
			</li>

			{% if photos.has_next %}
			<li>
				<a href="?page={{ photos.next_page_number }}">Next</a>
			</li>
			{% endif %}
		</ul>
	</nav>
</div>
{% endblock %}


{% block script %}
<script src="{% static 'js/photo/album_detail.js' %}"></script>
{% endblock %}

161028_Django_Day15/mysite-project/django_app/templates/photo/album_add.html
{% extends 'common/base.html' %}

{% block content %}
<div id="album_add">
	<h4>Album add</h4>
	<form action="" method="POST">{% csrf_token %}
		<div class="form-group">
			{{ form.title.label_tag }}
			{{ form.title }}
		</div>
		<div class="form-group">
			{{ form.description.label_tag }}
			{{ form.description }}
		</div>
		<button type="submit" class="btn btn-primary">Add album</button>
	</form>
</div>
{% endblock %}

161028_Django_Day15/mysite-project/django_app/templates/photo/album_detail.html
{% extends 'common/base.html' %}

{% block content %}
<div id="album-detail">
	<h4>{{ album.title }}</h4>
	<div>
		<span>{{ album.owner.email }}</span>
		{% if album.description %}
		<span>| {{ album.description }}</span>
		{% endif %}
	</div>
	<a href="{% url 'photo:photo_add' album_pk=album.pk %}" class="btn btn-primary btn-sm btn-top-right">
		<span class="glyphicon glyphicon-plus"></span>
		Add Photo
	</a>
	<a href="{% url 'photo:photo_multi_add' album_pk=album.pk %}" class="btn btn-primary btn-sm btn-top-right">
		<span class="glyphicon glyphicon-plus"></span>
		Add Multi Photo
	</a>
	<div class="photo-list">
		{% for photo in album.photo_set.all %}
		<div class="col-xs-6 col-md-3">
			<div class="thumbnail">
				<a href="{% url 'photo:photo_detail' pk=photo.pk %}">
					<img src="{{ photo.url_thumbnail }}" alt="">
				</a>
				<div class="caption">
					<div>
						<strong>{{ photo.title }}</strong>
					</div>
					<div>
						<span>{{ photo.owner.email }}</span>
						{% if photo.description %}
						<span>| {{ photo.description }}</span>
						{% endif %}
					</div>
					<div class="like-container">
						<form action="{% url 'photo:photo_like' pk=photo.pk like_type='like' %}" method="POST" class="like-form">{% csrf_token %}
							<button
								class="btn label
									{% if user in photo.like_users.all %}label-info
									{% else %}label-default
									{% endif %}"
							  type="submit"
								data-toggle="tooltip"
								data-placement="right"
								title="
									{% for user in photo.like_users.all|slice:'3' %}
										{{ user.email }}{% if not forloop.last %},
										{% endif %}

										{% if photo.like_users.count > 3 %}
										외 {{ photo.like_users.count|add:'-3' }}명
										{% endif %}
									{% endfor %}
								">
								<span class="glyphicon glyphicon-thumbs-up"></span>
								<span> {{ photo.like_users.count }}</span>
							</button>
						</form>

						<form action="{% url 'photo:photo_like' pk=photo.pk like_type='dislike' %}" method="POST" class="like-form">{% csrf_token %}
							<button
								class="btn label
									{% if user in photo.dislike_users.all %}label-danger
									{% else %}label-default
									{% endif %}"
							  type="submit"
								data-toggle="tooltip"
								data-placement="right"
								title="
									{% for user in photo.dislike_users.all|slice:'3' %}
										{{ user.email }}{% if not forloop.last %},
										{% endif %}

										{% if photo.dislike_users.count > 3 %}
										외 {{ photo.dislike_users.count|add:'-3' }}명
										{% endif %}
									{% endfor %}
								">
								<span class="glyphicon glyphicon-thumbs-down"></span>
								<span> {{ photo.dislike_users.count }}</span>
							</button>
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}


{% block script %}
<script>

</script>
{% endblock %}

161028_Django_Day15/mysite-project/django_app/templates/photo/album_list.html
{% extends 'common/base.html' %}

{% block content %}
<div id="album_list">
	<h4>Album list</h4>
	<a href="{% url 'photo:album_add' %}" class="btn btn-primary btn-sm btn-top-right">
		<span class="glyphicon glyphicon-plus"></span>
		Add Album
	</a>
	<ul class="list-group">
		{% for album in albums %}
		<li class="list-group-item">
			<span class="badge">{{ album.photo_set.count }}</span>
			<div>
				<a href="{% url 'photo:album_detail' pk=album.pk %}">
					<strong>{{ album.title }}</strong>
				</a>
			</div>
			<span>{{ album.owner.email }}</span>
			{% if album.description %}
			<span> | {{ album.description }}</span>
			{% endif %}
		</li>
		{% endfor %}
	</ul>
</div>
{% endblock %}

161028_Django_Day15/mysite-project/django_app/templates/photo/photo_add.html
{% extends 'common/base.html' %}

{% block content %}
<div id="photo-add">
	<h4>Photo add</h4>
	<form action="" enctype="multipart/form-data" method="POST">{% csrf_token %}
		<div class="form-group">
			{{ form.title.label_tag }}
			{{ form.title }}
			{{ form.title.errors }}
		</div>
		<div class="form-group">
			{{ form.description.label_tag }}
			{{ form.description }}
			{{ form.description.errors }}
		</div>
		<div class="form-group">
			{{ form.img.label_tag }}
			{{ form.img }}
			{{ form.img.errors }}
		</div>
		<button type="submit" class="btn btn-primary">Add photo</button>
	</form>
</div>
{% endblock %}

161028_Django_Day15/mysite-project/django_app/templates/photo/photo_detail.html
{% extends 'common/base.html' %}

{% block content %}
<div id="photo-detail">
	<h4>{{ photo.title }}</h4>
	<p>{{ photo.description }} | {{ photo.owner.email }}</p>
	<img src="{{ photo.img.url }}" alt="" class="thumbnail photo-img">
	<div class="like-container">
		<form action="{% url 'photo:photo_like' pk=photo.pk like_type='like' %}?next={{ request.path }}" method="POST" class="like-form">{% csrf_token %}
			<button
				class="btn
					{% if user in photo.like_users.all %}btn-info
					{% else %}btn-default
					{% endif %}"
			  type="submit"
				data-toggle="tooltip"
				data-placement="right"
				title="
					{% for user in photo.like_users.all|slice:'3' %}
						{{ user.email }}{% if not forloop.last %},
						{% endif %}

						{% if photo.like_users.count > 3 %}
						외 {{ photo.like_users.count|add:'-3' }}명
						{% endif %}
					{% endfor %}
				">
				<span class="glyphicon glyphicon-thumbs-up"></span>
				<span> {{ photo.like_users.count }}</span>
			</button>
		</form>

		<form action="{% url 'photo:photo_like' pk=photo.pk like_type='dislike' %}?next={{ request.path }}" method="POST" class="like-form">{% csrf_token %}
			<button
				class="btn
					{% if user in photo.dislike_users.all %}btn-danger
					{% else %}btn-default
					{% endif %}"
			  type="submit"
				data-toggle="tooltip"
				data-placement="right"
				title="
					{% for user in photo.dislike_users.all|slice:'3' %}
						{{ user.email }}{% if not forloop.last %},
						{% endif %}

						{% if photo.dislike_users.count > 3 %}
						외 {{ photo.dislike_users.count|add:'-3' }}명
						{% endif %}
					{% endfor %}
				">
				<span class="glyphicon glyphicon-thumbs-down"></span>
				<span> {{ photo.dislike_users.count }}</span>
			</button>
		</form>
	</div>
</div>
{% endblock %}

161028_Django_Day15/mysite-project/django_app/templates/photo/photo_multi_add.html
{% extends 'common/base.html' %}

{% block content %}
<div id="photo-add">
	<h4>Photo multi add</h4>
	<form action="" enctype="multipart/form-data" method="POST">{% csrf_token %}
		<div class="form-group">
			{{ form.title.label_tag }}
			{{ form.title }}
			{{ form.title.errors }}
		</div>
		<div class="form-group">
			{{ form.description.label_tag }}
			{{ form.description }}
			{{ form.description.errors }}
		</div>
		<div class="form-group">
			{{ form.img.label_tag }}
			{{ form.img }}
			{{ form.img.errors }}
		</div>
		<button type="submit" class="btn btn-primary">Add multi photo</button>
	</form>
</div>
{% endblock %}